"""Adiciona campos de automação de benefícios ao Funcionario

Revision ID: 0b3acbe25c17
Revises: 6032c0d93faa
Create Date: 2025-08-27 14:50:03.791498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3acbe25c17'
down_revision = '6032c0d93faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_trabalho', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vale_transporte_diario', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vale_alimentacao_mensal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vale_refeicao_mensal', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('vale_refeicao_mensal')
        batch_op.drop_column('vale_alimentacao_mensal')
        batch_op.drop_column('vale_transporte_diario')
        batch_op.drop_column('jornada_trabalho')

    # ### end Alembic commands ###
