"""Cria a estrutura inicial da base de dados

Revision ID: 1f36119db3cd
Revises: 
Create Date: 2025-08-19 11:21:11.535698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f36119db3cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status_assinatura', sa.String(length=20), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('plano', sa.String(length=50), nullable=False),
    sa.Column('responsavel_contrato', sa.String(length=150), nullable=True),
    sa.Column('data_contrato', sa.DateTime(), nullable=True),
    sa.Column('duracao_contrato_meses', sa.Integer(), nullable=True),
    sa.Column('data_vencimento_pagamento', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('monitorar_reputacao', sa.Boolean(), nullable=True),
    sa.Column('google_reviews_url', sa.String(length=255), nullable=True),
    sa.Column('reclame_aqui_url', sa.String(length=255), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_token', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('reputacao_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('nota_google', sa.Float(), nullable=True),
    sa.Column('total_avaliacoes_google', sa.Integer(), nullable=True),
    sa.Column('nota_reclame_aqui', sa.Float(), nullable=True),
    sa.Column('total_reclamacoes_reclame_aqui', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('whatsapp_numero', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('chamada_id', sa.String(length=100), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=True),
    sa.Column('csat', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversa_whats_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=50), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('agente_atribuido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agente_atribuido_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('remetente', sa.String(length=150), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('data_recebimento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anotacao_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket_suporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem_whats_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remetente', sa.String(length=20), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_whats_app.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem_whats_app')
    op.drop_table('anotacao_ticket')
    op.drop_table('ticket_suporte')
    op.drop_table('email')
    op.drop_table('conversa_whats_app')
    op.drop_table('avaliacao')
    op.drop_table('usuario')
    op.drop_table('reputacao_historico')
    op.drop_table('empresa')
    # ### end Alembic commands ###
