"""Adiciona foto de perfil e documentos ao funcionário

Revision ID: 5e25ff8b6255
Revises: 4266c5e64b1b
Create Date: 2025-08-27 09:04:33.915606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e25ff8b6255'
down_revision = '4266c5e64b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficios_funcionarios',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_beneficio', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controle_ponto',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('entrada_1', sa.Time(), nullable=True),
    sa.Column('saida_1', sa.Time(), nullable=True),
    sa.Column('entrada_2', sa.Time(), nullable=True),
    sa.Column('saida_2', sa.Time(), nullable=True),
    sa.Column('horas_trabalhadas', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('horas_extras', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folha_pagamento',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('horas_extras', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('irrf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vale_transporte', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vale_refeicao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_proventos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_descontos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_liquido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dias_trabalhados', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    op.drop_table('folha_pagamento')
    op.drop_table('documentos_funcionarios')
    op.drop_table('controle_ponto')
    op.drop_table('beneficios_funcionarios')
    # ### end Alembic commands ###
