"""Adiciona campo CBO ao modelo Cargo

Revision ID: 6032c0d93faa
Revises: 5e25ff8b6255
Create Date: 2025-08-27 11:08:07.348317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6032c0d93faa'
down_revision = '5e25ff8b6255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.drop_column('cbo')

    # ### end Alembic commands ###
