"""Adiciona permissao de acesso ao RH por usuario

Revision ID: 7a056c0e9273
Revises: a8f8a8682c85
Create Date: 2025-10-21 14:32:16.326140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a056c0e9273'
down_revision = 'a8f8a8682c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_rh_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('has_rh_access')

    # ### end Alembic commands ###
