"""Renomeia colunas de benefícios para valores diários

Revision ID: 9275fbf16c66
Revises: 99c534ecfad9
Create Date: 2025-08-27 17:33:40.089356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9275fbf16c66'
down_revision = '99c534ecfad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vale_alimentacao_diario', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vale_refeicao_diario', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('vale_alimentacao_mensal')
        batch_op.drop_column('vale_refeicao_mensal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vale_refeicao_mensal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vale_alimentacao_mensal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('vale_refeicao_diario')
        batch_op.drop_column('vale_alimentacao_diario')

    # ### end Alembic commands ###
