"""Adiciona campos de controle de benefícios ao Funcionario

Revision ID: 99c534ecfad9
Revises: 0b3acbe25c17
Create Date: 2025-08-27 15:05:28.160273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c534ecfad9'
down_revision = '0b3acbe25c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recebe_vt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recebe_va', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recebe_vr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('recebe_vr')
        batch_op.drop_column('recebe_va')
        batch_op.drop_column('recebe_vt')

    # ### end Alembic commands ###
