"""Adiciona atribuicao de agente a conversas

Revision ID: 9e6658caaf03
Revises: 
Create Date: 2025-08-15 15:54:11.678132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6658caaf03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa_whats_app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agente_atribuido_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['agente_atribuido_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa_whats_app', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agente_atribuido_id')

    # ### end Alembic commands ###
