"""Adiciona campos de status e monitoramento do agente ao Usuario

Revision ID: a8f8a8682c85
Revises: d1999dbc12ac
Create Date: 2025-10-20 14:52:13.767894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f8a8682c85'
down_revision = 'd1999dbc12ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_agent_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_monitoring', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_monitoring')
        batch_op.drop_column('last_agent_activity')

    # ### end Alembic commands ###
