"""Adiciona campos de token para agente de desktop

Revision ID: d1999dbc12ac
Revises: b1a2c3d4e5f6
Create Date: 2025-10-15 16:43:29.542181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1999dbc12ac'
down_revision = 'b1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desktop_login_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('desktop_token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['desktop_login_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('desktop_token_expiration')
        batch_op.drop_column('desktop_login_token')

    # ### end Alembic commands ###
