"""Adiciona funcionalidades de atribuição e histórico aos tickets

Revision ID: f38060cab6f9
Revises: 2d379bf68c76
Create Date: 2025-08-20 13:16:03.723980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38060cab6f9'
down_revision = '2d379bf68c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket_suporte.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anotacao_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_solution', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ticket_suporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_suporte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('anotacao_ticket', schema=None) as batch_op:
        batch_op.drop_column('is_solution')

    op.drop_table('ticket_atividade')
    # ### end Alembic commands ###
